# Generated by Django 5.2.1 on 2025-05-22 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_validade', models.DateField(verbose_name='Data de validade')),
                ('quantidade', models.IntegerField(default=1)),
                ('id_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.fornecedor')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.produto')),
            ],
            options={
                'unique_together': {('id_produto', 'id_fornecedor', 'data_validade')},
            },
        ),
    ]
